os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
install:
- ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
- ./scripts/travis/install-opentxs.sh "0.93.0" "${CXX}" "${TRAVIS_OS_NAME}"
before_script:
- ./scripts/travis/cppcheck_wrapper.sh ./src
- ./scripts/travis/clang-format-checker.sh
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/opentxs && make -j 2 && make test
- cd ..
before_deploy:
- ./scripts/travis/build_tar.sh "${TRAVIS_OS_NAME}"
deploy:
  provider: s3
  access_key_id: AKIAIR7XPKSU5OIGJ5IA
  secret_access_key:
    secure: iDrSuBkQOFwOk5ByP6hmidmhT4/jtW0uumHSZAz14OXLm9b5Jar6BgGdJg4Kxj22F3I2jbzjWxzzAk5DxfzaKkkHFz/DXGLbV+rD3h4vKEF6+xS2lgwfkzLwhablECFU9f9faQgZuKWJB+l/YekEP3jQH/+fW2Vg5Q/SBh2WUfU=
  bucket: monetas-builds
  skip_cleanup: true
  local-dir: s3
  upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}
  on:
    branch: ${TRAVIS_BRANCH}
branches:
  only:
  - master
  - develop
