#!/bin/sh

clang_bin=clang-format

if ! command -v clang-format >/dev/null ; then
    echo -n "error: please install clang-format == 8.* to use"
    echo    " this pre-commit git-hook"
    exit 1
fi

version=$(clang-format  --version | sed 's/clang-format version //' | head -c 1)

if ! (($version == 8)) ; then
    echo "Checking for clang-format version == 8.* ... failed"
    exit 1
fi

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

files=$(git diff --cached --name-only --diff-filter=AM $against | \
        grep -E '^(src|tests|include)' | grep pp$)
diffs=$(./scripts/build/clang-format-wrapper.sh "$files")
[ "$diffs" ] || exit 0
echo Found C++ code style formatting issues:
printf "%s\n" "$diffs"
exit 1
